const sqlite3 = require('sqlite3').verbose();
const db = new sqlite3.Database('./loans.db');

// Provided NBFC List
const nbfcList = [
    "Abhinav Hire Purchase Ltd.",
    "Abs Leasing & Financing (I) Ltd.",
    "Acg Sons Financiers Ltd",
    "Achal Finance Ltd.",
    "Adarsh Financiers Ltd.",
    "Adarsh General Motor Financers Ltd",
    "Adayar Finance & Leasing Ltd",
    "Advait Auto Finance Ltd.",
    "Ajanta Instalments Limited",
    "Ajmani Leasing & Finance Ltd.",
    "Akal Finlease Ltd.",
    "Akal Hire Purchase Ltd.",
    "Akme Fintrade (India) Ltd",
    "Alagendran Finance Ltd.",
    "Alamgir Motor Finance Ltd.",
    "Alpha Motor Finance Limited",
    "Alpic Finance Ltd.",
    "Amarjit Finance Ltd.",
    "Amarpreet Finance Ltd.",
    "Ambica Instalments Limited",
    "Amrit Hire Purchase Ltd.",
    "Amroha Tradefin Limited",
    "Anand Lakshmi Finance Ltd.",
    "Anmol Financial Services Ltd.",
    "Anna Finance Limited",
    "Annapoorna Finvest Ltd.",
    "Anuvish Finance Limited",
    "Apna Finance (India) Ltd",
    "Aps Hire Purchase Ltd.",
    "Aquila Finance Limited",
    "Arcot Finance And Agency Ltd",
    "Arman Lease And Finance Ltd.",
    "Arora Fincap Ltd.",
    "Arshdeep Finance Ltd.",
    "Aruna Leasing & Finance Ltd.",
    "Askrija Finance & Leasing Pvt Ltd",
    "Auram Leasing & Finance Ltd.",
    "Auto & Household Finance (India) Ltd.",
    "Automobile & General Finance Company (P) Ltd.",
    "Avon Capital Services Ltd.",
    "B.D. Credits Limited",
    "B.R.M. Lease & Credit Pvt Ltd.",
    "B.V.Finance & Leasing Ltd.",
    "Baba Farid Investment Pvt. Ltd.",
    "Baba Finance Pvt. Ltd.",
    "Baba Puran Dass Financial Services Ltd.",
    "Baithul Islam Finance & Investment (India) Pvt.Ltd.",
    "Bajaj Auto Finance Ltd.",
    "Balaji Fund Growth Ltd.",
    "Balaji Indofin Limited",
    "Balaji Instalments Limited",
    "Balaji Instalments Supply Ltd.",
    "Bansal Credits Limited",
    "Bansal Motor Finance Ltd.",
    "Barkha Financiers Ltd.",
    "Barkha Instalments Ltd.",
    "Basist Leasing & Finance Company",
    "Bathla And Co. Ltd.",
    "Beeru Brothers Finance Ltd",
    "Bell Leasing And Hire Purchase Limited",
    "Berar Finance Ltd.",
    "Bhagwan Instalments Limited",
    "Bhagwn H.P Limited",
    "Bhanot Finance Ltd.",
    "Bharat Finance & Industries Ltd.",
    "Bhasin Credit Aid Ltd.",
    "Bhaskar Narayan Finance Co. (P) Ltd.",
    "Bhojwani Leasing & Finance Ltd.",
    "Bhonsale Leasing & Finance Co. Ltd.",
    "Bijnor Leasing (P)Limited",
    "Bikaner Commercial Co Ltd",
    "Bindiya Capital Ltd",
    "Birla Global Finance Ltd.",
    "Black Diamond Finance Ltd",
    "Blue Jay Finlease Ltd.",
    "Brd Securities Ltd",
    "Brijendra Hire Purchase & Finance Ltd",
    "Brr Leafin Pvt. Ltd.",
    "Canbank Factors Ltd.",
    "Carthic Credits Ltd",
    "Ceejay Finance Limited",
    "Chadha Finance Pvt Ltd.",
    "Chambers Equity & Financial Co. Ltd.",
    "Chandan Credits Ltd",
    "Chandandhara Finance Ltd",
    "Chartered Leasing (P) Ltd.",
    "Chatha Financial Services Ltd.",
    "Chatha Financiers Ltd.",
    "Chemm Finance Ltd.",
    "Chenai Financeco Ltd.",
    "Chinmay Finlease P. Ltd.",
    "Chittrakoot Motor Finance Limited",
    "Cholamandalam Investments & Finance Co Ltd",
    "Concord Marketing & Financiers Pvt. Ltd.",
    "Dada Dev Finance & Leasing Pvt Ltd.",
    "Daksum Finance Ltd.",
    "Dandona Finance Ltd.",
    "Dani Finlease Ltd.",
    "Dani Trading & Investment Ltd.",
    "Dar Credit & Capital Ltd",
    "Dashmesh Fin Invest Co. Ltd.",
    "Deccan Finance Ltd",
    "Deep Dhalleke Auto Financiers Ltd.",
    "Deep Finance Ltd.",
    "Deep Fincap Ltd.",
    "Deep Finvest Ltd.",
    "Deep Hire Purchase Ltd.",
    "Deep Motor Finance Ltd.",
    "Delhi Properties & Building Society Ltd.",
    "Delhi Punjab Finance Co. Ltd.",
    "Denovo Leasing & Investments Ltd",
    "Dewan Motors Investment & Finance Ltd.",
    "Dfl Finance Ltd.",
    "Dhaliwal Finance Private Limited",
    "Dhanalakshmi Motors Finance Pvt. Ltd",
    "Dhandapani Finance Ltd",
    "Dhara Motor Finance Ltd.",
    "Dhp Leasing Ltd.",
    "Diamond Fincap Ltd.",
    "Diganta Investments & Finance Co. Ltd.",
    "Dignity Motors Finance Ltd.",
    "Dinesh Commercial Finance Ltd.",
    "Dove Finance Ltd",
    "Ds Brar Finance Co. Pvt. Ltd.",
    "Dsp Finpriint Ltd.",
    "Dutta Financiers (I) Ltd.",
    "Ekjot Advances Ltd.",
    "Elegant Finvest Pvt. Ltd.",
    "Empire Securities & Capital Ltd.",
    "Enn Financial Services Ltd",
    "Ennobel India Savings & Investments Co Ltd.",
    "Ennoble Leasing (India)Ltd.",
    "Escorts Finance Limited",
    "Esn Finance & Capital Services Ltd.",
    "Ess Dee Hire Purchase Ltd.",
    "Ever Trust Finance (India) Ltd",
    "Excellent Fin-Invest Ltd",
    "Ex-Servicemen Hire Purchase Finance Ltd.",
    "Fair Deal General Finance Co. Ltd.",
    "Fairdeal Leasing Ltd.",
    "Finance House (India) Pvt Ltd.",
    "Fincap Financial Corporation Limited",
    "First Leasing Co. Of India Ltd",
    "Fortis Financial Services Ltd.",
    "Fortress Financial Services Ltd.",
    "Forward Securities Ltd.",
    "Fraternal Credit & Financial Services Ltd",
    "Gajraj Motor & General Finance Co. Ltd.",
    "Galada Finance Ltd",
    "Gayaprasad Hiralal Ltd",
    "Gee Cee Advance Advance Ltd",
    "Gilada Finance & Investments Ltd",
    "Gill & Virk Finance Co. Ltd.",
    "Gn Vasavi Finance Ltd.",
    "Gobind Finance & Properties Ltd.",
    "Gokul Finance & Investment Company Ltd.",
    "Golden India Leasing & Finance Ltd.",
    "Goli Finance Limited",
    "Gondwana Leasing & Finance Pvt. Ltd.",
    "Goodluck Advances & Finlease Limited",
    "Gopalka Auto Finance Ltd",
    "Gopalka Finance Corporation Ltd",
    "Gove Investments And Finance Co Ltd",
    "Greatfin Leasing & Credit Ltd.",
    "Gtp Finance Ltd",
    "Gujarat Lease Financing Ltd.",
    "Gujarat State Financial Services Ltd.",
    "Gupta Instalments Supply Limited",
    "Gupta Motor & General Finance (P) Ltd.",
    "Gurukirpa Finvest Ltd.",
    "Hallmark Leasing & Finance Ltd",
    "Hargobind Sahib Hire Purchase Ltd.",
    "Harinder Hire Purchase Ltd.",
    "Harinder Investments Ltd.",
    "Harinder Leasing Ltd.",
    "Harsolia Finance Ltd",
    "Haryana Finance Private Limited",
    "Haryana State Industrial Development Corp.Ltd.",
    "Hastah Finances Ltd.",
    "Heritage Finlease Limited",
    "Hero Financial Services Ltd.",
    "Him Sikhar Saving & Finance Ltd.",
    "Himachal Motor & General Finance Ltd.",
    "Himgiri Hire Purchase Ltd.",
    "Hitin Motor & General Finance Co. Ltd.",
    "Honhar Investments Private Limited",
    "Hrd Fincap Ltd.",
    "IFCI Limited",
    "IKF Finance Limited",
    "India Cements Capital & Finance Ltd",
    "India Lease Development Limited",
    "India Securities Ltd.",
    "Indian Seamless Financial Services Ltd.",
    "Indo Asian Finance Ltd",
    "Inovoa Securities Ltd.",
    "Integrated Finance Co. Ltd.",
    "Inter State Finance Limited",
    "Investech Finance Ltd.",
    "Ishan Finlease P. Ltd.",
    "Isher Finance Pvt. Ltd",
    "J.C.Motor & Finance Company Ltd.",
    "J.K. Prime Investment & Leasing (I) Ltd.",
    "J.S.Hire Purchase Ltd.",
    "Jagat Leasing Ltd.",
    "Jai Savings And Hire Purchase (I)Ltd.",
    "Jalandhar Cargo Advances Ltd.",
    "Jaryal Motors Finance Co. Ltd.",
    "Jassi Hire Purchase Ltd.",
    "Jay Cee Finance Ltd.",
    "Jay Ganesh Instalments Ltd",
    "Jayabharat Credit Ltd.",
    "Jayalakshmi Credit Company Ltd.",
    "Jeba Finance Ltd",
    "Jenson & Nicholson Financial Services Limited",
    "Jindal Fincap Ltd.",
    "Jiwan Jyoti Deposits & Advances Ltd.",
    "Johal Investments Ltd.",
    "Ju-Ju Finance & Leasing Ltd",
    "K.C.Fincap Ltd.",
    "K.S.Capital Services Ltd",
    "K.Z.Leasing And Finance Ltd",
    "Kailash Auto Finance Limited",
    "Kamakhia Finance & Leasing Ltd.",
    "Kamal Auto Finance Ltd",
    "Kanak Instalments Limited",
    "Kanakadurga Leasing & Finance Ltd.",
    "Karimnagar Vijay Hire Purchase & Leasing (P) Ltd.",
    "Kartar Leasing Pvt Ltd.",
    "Karur Gayathiri Finance Ltd",
    "Karvy Consultants Ltd.",
    "Katwa Finlease Ltd",
    "Kaveri Credits (India) Pvt. Ltd.",
    "Kay Ess Hire Purchase Pvt. Ltd.",
    "Kelachandra Leasing & Finance Ltd.",
    "Kerala Power Finance Corporation Ltd.",
    "Kesavaya Finance Ltd.",
    "Kfic Financial Services Ltd.",
    "Kgk Finance Ltd",
    "Khiwasara Finance & Leasing Ltd.",
    "Kim Investments Ltd.",
    "Kissan Finvest Ltd.",
    "Kls Finance & Investments Ltd.",
    "Kogta Financial (India) Ltd",
    "Kopal Motor And General Finance Ltd.",
    "Kuldip Finance Ltd.",
    "Kusalava Finance Limited",
    "Labham Finance Ltd.",
    "Lakshmi General Finance Ltd",
    "Laxman Leafin Ltd.",
    "Lbira Auto & General Finance Ltd.",
    "Lfc Hire Purchase Company Limited",
    "Libra Finance Ltd.",
    "Libra Leasing Ltd.",
    "Lion Financial Services Ltd.",
    "Lipi Finstock Ltd.",
    "Lotus Hire Purchase Ltd.",
    "Lrn Finance Ltd",
    "Lsp Finance Ltd",
    "Lyca Finance Limited",
    "Lynx Investments (India) Ltd.",
    "M.G. Brothers Finance Ltd.",
    "M/S.Grihastha Finance Limited",
    "M/S.Opel Finance Limited",
    "Madhulika Finance Co.Ltd.",
    "Madhur Instalments Ltd.",
    "Madras Credit And Investments Ltd",
    "Mahaveer Finance India Ltd",
    "Mahaveer Leafin & Holdings Ltd.",
    "Mahavira Finlease Limited",
    "Mahendra Instalment Supply Ltd.",
    "Mahindra & Mahindra Financial Services Ltd.",
    "Majha Doaba Consultants & Finvest Ltd",
    "Majha Finance Ltd.",
    "Majha Investment Ltd.",
    "Majotra Financiers & Traders Pvt. Ltd.",
    "Malik Motor Finance Ltd.",
    "Malwa (Ludhiana) Motor Finance Ltd.",
    "Manapppuram General Finance And Leasing Ltd",
    "Mand Finance Ltd.",
    "Mand Hire Purchase Pvt. Ltd.",
    "Maneesha Finlease Limited",
    "Mango Securities Ltd.",
    "Manhar Finance Ltd.",
    "Manimajra Motor Finance Ltd.",
    "Manipal Finance Corporation Ltd",
    "Manisha Motor & General Finance Ltd.",
    "Mano Finance Ltd",
    "Manohar Finance India Ltd",
    "Mansar Finance Pvt. Ltd.",
    "Mansatta Finance & Leasing Ltd.",
    "Mantrana Finlease Ltd.",
    "Map Credit & Capital Limited",
    "Mas Financial Services Ltd.",
    "Master Leasing Ltd.",
    "Mayur Motor & General Finance Ltd.",
    "Micro Finance Limited",
    "Midland Financiers (Doaba) Ltd.",
    "Midland Motor Finance Co. Ltd.",
    "Mitter Finance Co. Ltd.",
    "Modern General Financiers Ltd.",
    "Moga Deposits & Advances Ltd.",
    "Moga Finance Ltd.",
    "Money Masters Leasing & Finance Ltd.",
    "Montgomery Finance Co. Ltd.",
    "Moonshine Finvest Pvt Ltd.",
    "Morinda Hire Purchase Ltd.",
    "Mrg Finance Ltd.",
    "Mudavoor Financial Services Ltd",
    "Mukat Finance Ltd.",
    "Mukunda Industrial Finance Ltd",
    "Mukut Finlease Ltd.",
    "Mulamoottil Consumer Credits Limited",
    "Multani Motor Finance Pvt. Ltd.",
    "Murudeshwara Finance & Leasing Ltd.",
    "Muthoot Capital Services Ltd",
    "Muthoot Leasing & Finance Ltd",
    "Mysore Leasing & Finance Ltd",
    "N.P. Automobile & Finance Ltd.",
    "N.S.Hire Purchase Ltd.",
    "Naini Fincap Limited",
    "Nalin Lease Finance Ltd.",
    "Namakkal Andavar Business Credits Ltd",
    "Nand Auto Hire Purchase Ltd.",
    "Nandambakkam Finance Co Pvt Ltd",
    "Nationwide Investments Ltd.",
    "Nau Nidh Finance Ltd.",
    "Nawanshahar Finance Ltd.",
    "Neel Gagan Finance Ltd.",
    "New India Financial Services Ltd.",
    "New Sethi Finance Company Ltd.",
    "Newline Finance Ltd",
    "Newlink Overseas Finance Ltd",
    "Nicco Uco Alliance Credit Ltd",
    "Nilanshu Hire Purchase Ltd",
    "Nimba Finance & Leasing Pvt.Ltd.",
    "North Link Fiscal & Capital Services Ltd.",
    "Northpole Finance Ltd.",
    "Novelty Finance Ltd.",
    "Npr Finance Ltd",
    "Om Shridevi Leasing & Finance (P) Ltd.",
    "Orient Resins Ltd.",
    "Padmavati Financial Service Limited",
    "Panaji Finance Pvt. Ltd.",
    "Panjbakhtar Finance Ltd.",
    "Paramvir Leasing & Finance Ltd.",
    "Pariskshat Financiers Ltd.",
    "Parnami Credits Limited",
    "Parv Financiers Ltd.",
    "Paul Merchants Limited",
    "Peejay Finance Co Ltd",
    "PHF (Punjab Haryana Auto) Finance Ltd.",
    "PHF Hire Purchase Ltd.",
    "Phf Investment Ltd.",
    "Phf Leasing Ltd.",
    "Pilibhit Finance Ltd.",
    "Pitampura Leasing & Housing Finance Ltd.",
    "Pkf Finance Ltd.",
    "Pnb Capital Services Ltd.",
    "Pondicherry Ind. Promotion Dev. &Investment Corporation Ltd",
    "Pondicherry Nidhi Ltd",
    "Pontiac Leasing Ltd",
    "Pooja Hire Purchase Ltd.",
    "Prayag Capitals India Ltd.",
    "Prem Hire Purchase Ltd",
    "Prince Finance Limited",
    "Proficient Leasing & Finance Ltd.",
    "Pugalur Finance (Karur) Ltd",
    "Punjab Kashmir Finance Ltd.",
    "Punjab Leasing Pvt. Ltd.",
    "Punjab Reliable Investments Pvt. Ltd.",
    "Pyar Finance Ltd.",
    "Raasi Finance & Investment Ltd.",
    "Raj Hire Purchase Limited",
    "Rajammal Rangasamy Finance Ltd",
    "Rajath Finance Ltd.",
    "Rajdhani Leasing & Industries Limited",
    "Rajkhatri Finance Ltd",
    "Rajouri Hire Purchase & Finance Ltd.",
    "Rakshit Motor & General Finance Ltd.",
    "Ram Nath & Co. Financiars Ltd.",
    "Ramayan Auto Financiers Ltd.",
    "Ramir Finance & Leasing Co. Ltd.",
    "Ranni General Finance & Hire Purchase Ltd.",
    "Rattan Hire Purchase Ltd.",
    "Reliable Agro Engg. Services Pvt. Ltd.",
    "Reliant Hire Purchase Company Limited",
    "Rivaz Finance Limited",
    "Rkd Financial Services Ltd.",
    "Rohilkhand Financiers Limited",
    "S.A. Services Limited",
    "S.E. Investments Limited",
    "S.N.Hire Purchase Ltd.",
    "Sagar Deposits & Advances Ltd.",
    "Sagar Leasefin Ltd",
    "Sagar Motor Finance Ltd.",
    "Sahara India Financial Corporationltd.",
    "Sahyog Fincap Ltd",
    "Saibala Finance Ltd",
    "Sajan Hire Purchase Ltd.",
    "Sakthi Finance Ltd",
    "Samra Finance & Properties Ltd.",
    "Samra Leasing Ltd.",
    "Samrat Motor Finance Ltd.",
    "Sandhu Auto Deposits Ltd.",
    "Sandy Leasing Limited",
    "Sangam Hire Purchase Ltd",
    "Sanghvi Investment & Leasing Ltd.",
    "Sangrama Motor Finance (India) Ltd.",
    "Sanyog Finance & Investment Pvt. Ltd.",
    "Saral Motor & General Finance Ltd.",
    "Saraswathy Ganesan Finance Co Ltd",
    "Sargodha Securities Pvt. Ltd.",
    "Sarita Finance Ltd.",
    "Sarnath Finance Limited",
    "Sarvesh Automobile Finance Ltd.",
    "Sarvotam Leasing & Real Estate Ltd.",
    "Satin Creditcare Network Ltd.",
    "Satwari Investment (J&K) Pvt. Ltd.",
    "Satya Prakash Capital Investment Ltd",
    "Savandapoor Finance & Leasing Ltd",
    "Savera Credits Ltd.",
    "Sawhney Financiers Jammu Pvt. Ltd.",
    "Scf (Sarvotam Credits & Finance) Fin. Ltd.",
    "Sea Lord Hire Purchase Ltd.",
    "Sehajpal Finance & Investment Ltd.",
    "Sekhon Motor Finance Limited",
    "Selvaganapathy Leasing & Finance Ltd",
    "Seyad Shariat Finance Ltd",
    "Sgr Financial Services Ltd.",
    "Shaan Finance Ltd",
    "Shabnam Leasing & Finance Limited",
    "Shakumbri Motor & General Finance Ltd.",
    "Shane Haryana Finlease Ltd.",
    "Sheen Finance & Investment (I) Ltd",
    "Sheikh Farid Finvest Ltd.",
    "Shine Blue Hire Purchase Ltd.",
    "Shiromani Finance Ltd",
    "Shiromani Leasing And Finance Ltd.",
    "Shrachi Securities Ltd",
    "Shre Pathrakali Finance Co Ltd",
    "Shree Kalyani Leasing & Finance Ltd.",
    "Shree Om Finvest Ltd.",
    "Shri Sai Finlease Pvt. Ltd",
    "Shriram City Union Finance Ltd",
    "Shriram Investments Ltd",
    "Shriram Overseas Finance Ltd",
    "Shriram Transport Finance Co Ltd",
    "Shriram Truck Finance Company Ltd",
    "Sibar Finance Ltd.",
    "Sidhu Leasing & Finance Co. Ltd.",
    "Simmi Finance Ltd.",
    "Sindhu Trade Links Limited",
    "Singh Finance Ltd",
    "Singh Motors Hire Purchase Company Limited",
    "Siri Auto Financiers Private Ltd.",
    "Sivagami Finance & Investments Ltd",
    "Skylark Deposits & Advances Ltd.",
    "Skylark Motor & General Finance Ltd.",
    "Sml Finance Ltd",
    "Social Leasing (India) Ltd.",
    "Som Datt Finance Corporation Ltd",
    "Sona Finance Ltd.",
    "Soni Moni Credit Centre Pvt. Ltd.",
    "Spr Finance Ltd.",
    "Sreeragh General Finance Ltd.",
    "Srei International Finance Ltd",
    "Sri Ganesh Anand Leasing & Finance Ltd.",
    "Sri Janardhana Credits Ltd",
    "Sri Mappillai Vinayagar Fin (Madurai) Ltd",
    "Sri Ramalingeswara Leasing & Autofin (P) Ltd.",
    "Sri Sai Siri Finance And Leasing Ltd.",
    "Sri Selvanarayana Finance Ltd",
    "Sri Vijayaram Hire Purchase & Leasing Finance Pvt Ltd",
    "Star Instalments Supply Company Limited",
    "Subitha Leasing Company Limited",
    "Sudershan Hire Purchase Ltd",
    "Sufala Finance (P) Ltd.",
    "Sukh Chain Finance Co. Ltd.",
    "Sukhbans Finance Co. Ltd.",
    "Sukhchain Hire Purchase Ltd.",
    "Sundaram Finance Ltd",
    "Surjit Hire Purchase Ltd.",
    "Swami Hire Purchase Ltd.",
    "Swarn Finance Ltd.",
    "Swarna Securities Limited",
    "Syal Finance Ltd.",
    "Syal Investment Ltd.",
    "Syal Leasing Ltd.",
    "Tamil Nadu Bus Operators Finance Corporation Ltd",
    "Tamil Nadu Power Finance & Infrastructure Development Corporation Ltd.",
    "Tamilnadu Industrial Development Corpn. Ltd.",
    "Tamilnadu Transport Dev. Finance Corpn. Ltd.",
    "Tata Finance Ltd.",
    "Tata Investment Corporation Ltd.",
    "Tci Finance Limited",
    "Tenco Hire Purchase & Leasing Co. Ltd",
    "Thakar Investments Ltd.",
    "Thayar Overseas Finance Ltd",
    "The Delhi Safe Deposit Company Ltd.",
    "The Gicc Ltd",
    "The Industrial Credit & Investments Corporation Of India Ltd.",
    "The Instalment Supply Limited",
    "The Jullundur Hire Purchase Ltd.",
    "The Motor & General Finance Ltd.",
    "The New Globe Financiers Limited",
    "The Peerless General Finance &Investment Co Ltd",
    "The Secured Savings And Investment Ltd",
    "The Transport Finance Ltd.",
    "Thind Finance Pvt. Ltd.",
    "Thirunindra Narayanan Finance & Investment Pvt Ltd",
    "Tirupati Balaji Finance Co Ltd.",
    "Tirupati Services Limited",
    "Toor Finance Co. Ltd.",
    "Tourism Finance Corp. Of India Ltd.",
    "Trancity Finance And Leasing Pvt Ltd",
    "Trans Asia Auto & General Finance Ltd.",
    "Transworld Hire Purchase India Ltd",
    "Transworld Leasing Ltd.",
    "Trc Financial Services Ltd.",
    "Trikaal Leasing & Finance",
    "Tripund Motor & General Finance Ltd.",
    "Trishul Motor & General Finance Ltd.",
    "True Blue Finlease Limited",
    "True Link Finance Limited",
    "Tvs Finance Ltd",
    "Twin Cities Investments And Finances Ltd.",
    "Ujagar Advances Ltd.",
    "Umeed Investments (P) Ltd.",
    "Umeed Leasing & Finance Pvt. Ltd.",
    "Unity Securities And Finance Ltd.",
    "Upasana Finance Ltd",
    "Uttam Chand Arora Leasing & Finance Ltd.",
    "V & C Vaults & Finance Ltd.",
    "V.A.P. Finance Ltd",
    "V.N. Credits Limited",
    "V.V.D. Finance & Leasing Ltd",
    "Vaishali Motors Finace Limited",
    "Vardhan Properties & Investment Ltd.",
    "Vasu Senniappa Finance Pvt Ltd",
    "Venkatadri Financial Services Ltd.",
    "Verinder Finance",
    "Verinder Finance Ltd.",
    "Vijay Hemant Finance & Estates Ltd",
    "Vijay Hire Purchase & Leasing Ltd.",
    "Vijaya Finance Limited",
    "Vikas Profin Limited",
    "Vikramashila Finance And Leasing Ltd.",
    "Vinman Finance & Leasing Ltd.",
    "Virk Hire Purchase Ltd.",
    "Vishal Finlease P. Ltd.",
    "Visharad Automobile Financiers Ltd.",
    "Vishwa Gayatri Hire Purchase & Finance Ltd.",
    "Vivek Hire Purchase & Leasing Ltd",
    "Vivek Motor Finance Ltd.",
    "Wall Street Finance Ltd.",
    "Wellshine Investments & Fin Services Ltd",
    "West Bengal Industrial Development Corpn. Ltd",
    "West Bengal Infrastructure Development Finance Corpn Ltd",
    "Word Portfolio Finance & Leasing Ltd.",
    "Worth Capital Finance Pvt. Ltd.",
    "Yashika Leasing & Financial Services Ltd.",
    "Yogindera Finance Limited"
];

db.serialize(() => {
    // 1. Create table
    db.run(`CREATE TABLE IF NOT EXISTS banks (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        bank_name TEXT UNIQUE NOT NULL
    )`);

    // 2. Insert all provided NBFC names
    const stmt = db.prepare(`INSERT OR IGNORE INTO banks (bank_name) VALUES (?)`);
    nbfcList.forEach(bank => stmt.run(bank));
    stmt.finalize();

    console.log("Successfully seeded 568 NBFC/Bank entries into SQLite database!");
});

db.close();